# Generated by Django 4.0.3 on 2022-03-24 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carstate',
            fields=[
                ('states', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='cartype',
            fields=[
                ('types', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='premises',
            fields=[
                ('name', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('space', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('state', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='lots',
            fields=[
                ('lotId', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=3)),
                ('price', models.PositiveIntegerField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='parkingApp.status')),
            ],
        ),
        migrations.CreateModel(
            name='favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav', to='parkingApp.lots')),
            ],
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('platenumber', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=150)),
                ('carstate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='parkingApp.carstate')),
                ('cartype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='parkingApp.cartype')),
            ],
        ),
        migrations.CreateModel(
            name='businessusers',
            fields=[
                ('businessId', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=150)),
                ('fullname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('dividents', models.IntegerField(default=0)),
                ('premises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prem', to='parkingApp.premises')),
            ],
        ),
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('bookingId', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=150)),
                ('platenumber', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('stop', models.TimeField()),
                ('bill', models.PositiveIntegerField()),
                ('lots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lot', to='parkingApp.lots')),
            ],
        ),
    ]
