# Generated by Django 3.0.3 on 2022-03-24 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lots',
            name='premises',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='premis', to='parkingApp.premises'),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
