# Generated by Django 3.0.3 on 2022-03-24 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0002_auto_20220324_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='user',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='lots',
            name='premises',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='premis', to='parkingApp.premises'),
        ),
    ]
